### PR TITLE
Change a+im*b to complex(a,b)

### PR DESCRIPTION
**Pull request by araujoms**
This undoes the hack I had done in #831, thanks to jump-dev/JuMP.jl#3734.

### CODE REVIEW

**Comment by odow** [comment]
You must also change the lower bound of JuMP in any `Project.toml`s

**Comment by odow** [comment]
Then a separate issue is  https://github.com/jump-dev/Hypatia.jl/blob/master/examples/Project.toml
is missing a `[compat]` section.

**Comment by araujoms** [comment]
Oh, thanks for finding it! I'll add the necessary `[compat]` then when we have the new version of JuMP.

**Comment by araujoms** [comment]
Now with JuMP 1.22 it's working. Could you also tag a new Hypatia release?

**Pull request merged**
